---
- name: Update apt cache (max 1h old)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required OS packages
  ansible.builtin.apt:
    name:
      - nftables
      - ca-certificates
      - logrotate
      - jq
      - libcap2-bin                # pour setcap (cap_ipc_lock si besoin)
      - selinux-basics             # support SELinux Debian (optionnel)
      - selinux-policy-default
      - policycoreutils
    state: present

- name: Ensure nftables is enabled and running
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true
