---
galaxy_info:
  role_name: openstack_fip
  author: DSI
  description: Failover de Floating IP OpenStack via API Neutron pour HAProxy.
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: [trixie]
  galaxy_tags: [openstack, neutron, haproxy, failover, ha]

dependencies: []
