---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart fip-failover timer
  ansible.builtin.systemd:
    name: openbao-fip-failover.timer
    state: restarted
    enabled: true
